authentik:
  secret_key: "super-secret-key"

postgresql:
  enabled: true
  auth:
    username: authentik
    password: authentikpass
    database: authentik

  primary:
    persistence:
      enabled: true
      size: 10Gi

redis:
  enabled: true
  master:
    persistence:
      enabled: true
      size: 5Gi

server:
  replicas: 2

worker:
  replicas: 2